### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by NoahNxT** [jonassiewertsen/statamic-how-to-addon#27]
when trying to install the package I get this error:

 [InvalidArgumentException]                                                                                                                   
  Package jonassiewertsen/statamic-how-to-addon has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version
  
  my versions:
  Laravel 8.0
  composer 2.0.14
  php 8.0
  Statamic 3.2.14

**Comment by jonassiewertsen** [comment]
What about now @NoahNxT 

Your're right that packagist did not pick up the latest version. It's on auto update and I can't explain what happened. 
Anyways, I did use the manual update trick which did the trick as it does look. 

https://packagist.org/packages/jonassiewertsen/statamic-how-to-addon

Sorry for the trouble! You should be update to the latest version now.
